/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formDb;

/**
 *
 * @author ASUS
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class frmHewan extends javax.swing.JFrame {

    /**
     * Creates new form frmHewan
     */
    public Statement st;
    public ResultSet rs;
    Connection cn = Koneksi.KoneksiDatabase.BukaKoneksi();
    public frmHewan() {
        initComponents();
        TampilData();
    }
    private void Bersih(){
       txtid.setText("");
       txtid_obat.setText("");
       txtid_pemilik.setText("");
       txtid_species.setText("");
       txtnama.setText("");
       txthabitat.setText("");
       
       Btnsimpan.setText("Simpan ");
       txtid.setEditable(true);
    }
    private void CariData(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM hewan WHERE"+ Cmbcari.getSelectedItem().toString()+"LIKE'%" + TxtCari.getText()+"%'");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nomor");
            model.addColumn("id");
            model.addColumn("id_obat");
            model.addColumn("id_pemilik");
            model.addColumn("id_species");
            model.addColumn("nama");
            model.addColumn("habitat");
            
            int no =1;
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            
            while (rs.next()){
                Object[] data ={
                    no ++,
                    rs.getString ("id"),
                     rs.getString ("id_obat"),
                      rs.getString ("id_pemilik"),
                       rs.getString ("id_species"),
                        rs.getString ("nama"),
                         rs.getString ("habitat")
                };
                model.addRow(data);
                Tbldata.setModel(model);
            }
        } catch (Exception e) {
        }
    }
    private void TampilData(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM hewan");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nomor");
            model.addColumn("id");
            model.addColumn("id_obat");
            model.addColumn("id_pemilik");
            model.addColumn("id_species");
            model.addColumn("nama");
            model.addColumn("habitat");
            
            int no =1;
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            
            while (rs.next()){
                Object[] data ={
                    no ++,
                    rs.getString ("id"),
                     rs.getString ("id_obat"),
                      rs.getString ("id_pemilik"),
                       rs.getString ("id_species"),
                        rs.getString ("nama"),
                         rs.getString ("habitat")
                };
                model.addRow(data);
                Tbldata.setModel(model);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtid_obat = new javax.swing.JTextField();
        txtid_pemilik = new javax.swing.JTextField();
        txtid_species = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txthabitat = new javax.swing.JTextField();
        Btnsimpan = new javax.swing.JButton();
        Btnhapus = new javax.swing.JButton();
        Btnbatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbldata = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Cmbcari = new javax.swing.JComboBox<>();
        TxtCari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("ID Obat");

        jLabel3.setText("ID Pemilik");

        jLabel4.setText("ID Species");

        jLabel5.setText("Nama");

        jLabel6.setText("Habitat");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtid_pemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_pemilikActionPerformed(evt);
            }
        });

        txthabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthabitatActionPerformed(evt);
            }
        });

        Btnsimpan.setText("Simpan");
        Btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsimpanActionPerformed(evt);
            }
        });

        Btnhapus.setText("Hapus");
        Btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnhapusActionPerformed(evt);
            }
        });

        Btnbatal.setText("Batal");
        Btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbatalActionPerformed(evt);
            }
        });

        Tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "id_obat", "id_pemilik", "id_species", "nama", "habitat"
            }
        ));
        Tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbldata);

        jLabel7.setText("Cari Data");

        Cmbcari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "id_obat", "id_pemilik", "id_species", "nama", "habitat" }));

        TxtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCariKeyPressed(evt);
            }
        });

        jLabel8.setText("TABEL HEWAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(Cmbcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtCari))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthabitat)
                            .addComponent(txtnama)
                            .addComponent(txtid_species)
                            .addComponent(txtid)
                            .addComponent(txtid_obat)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btnsimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btnhapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btnbatal)
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addComponent(txtid_pemilik))
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtid_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtid_pemilik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtid_species, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txthabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnsimpan)
                    .addComponent(Btnhapus)
                    .addComponent(Btnbatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Cmbcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtid_pemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_pemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_pemilikActionPerformed

    private void BtnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsimpanActionPerformed
        // TODO add your handling code here:
       try {
    st = cn.createStatement();
    // Check if any of the text fields are empty
    if (txtid.getText().equals("") || 
        txtid_obat.getText().equals("") || 
        txtid_pemilik.getText().equals("") || 
        txtid_species.getText().equals("") || 
        txtnama.getText().equals("") || 
        txthabitat.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Data tidak boleh ada yang kosong", "Validasi data ", JOptionPane.INFORMATION_MESSAGE);
        return; // Return if any field is empty
    }

    if (Btnsimpan.getText().equals("Simpan")) { // Use .equals() to compare strings
        String cek = "SELECT * FROM hewan WHERE id = '" + txtid.getText() + "'";
        rs = st.executeQuery(cek);
        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "Maaf, data ini sudah ada.");
        } else {
            // Corrected SQL statement to insert data
            String sql = "INSERT INTO hewan VALUES ('" + txtid.getText() + "','" + txtid_obat.getText() + "','" + txtid_pemilik.getText() + "','" + txtid_species.getText() + "','" + txtnama.getText() + "','" + txthabitat.getText() + "')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            Bersih();
            TampilData();
            
        }
    } else {
        
        // Handle other actions if needed
        String update = "UPDATE hewan SET id_obat = '" + txtid_obat.getText()+
               
                "',id_pemilik ='" + txtid_pemilik.getText()+
                 "',id_species ='" + txtid_species.getText()+
                 "',nama ='" + txtnama.getText()+
                 "',habitat ='" + txthabitat.getText()+
                 "' WHERE id = '" + txtid.getText()+"'";
        
        st.executeUpdate(update);
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        Bersih();
        TampilData();
        
                
    }
} catch (Exception e) {
    e.printStackTrace(); // Print the exception details for debugging
    JOptionPane.showMessageDialog(null, e);
}

            
    }//GEN-LAST:event_BtnsimpanActionPerformed

    private void txthabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthabitatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthabitatActionPerformed

    private void TbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbldataMouseClicked
        // TODO add your handling code here:
        txtid.setText(Tbldata.getValueAt(Tbldata.getSelectedRow(),1).toString());
         txtid_obat.setText(Tbldata.getValueAt(Tbldata.getSelectedRow(),2).toString());
          txtid_pemilik.setText(Tbldata.getValueAt(Tbldata.getSelectedRow(),3).toString());
           txtid_species.setText(Tbldata.getValueAt(Tbldata.getSelectedRow(),4).toString());
            txtnama.setText(Tbldata.getValueAt(Tbldata.getSelectedRow(),5).toString());
             txthabitat.setText(Tbldata.getValueAt(Tbldata.getSelectedRow(),6).toString());
             
             
             txtid.setEditable(false);
             Btnsimpan.setText("Ubah");
    }//GEN-LAST:event_TbldataMouseClicked

    private void BtnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnhapusActionPerformed
        // TODO add your handling code here:
        if (txtid.getText().equals("")) {
        JOptionPane.showMessageDialog(this,"Silahkan pilih Data yang akan dihapus");
    } else {
        int jawab = JOptionPane.showConfirmDialog(null, "Data ini akan dihapus, apakah anda ingin melanjutkan?", "KONFIRMASI", JOptionPane.YES_NO_OPTION);
        if (jawab == JOptionPane.YES_OPTION) {
            // Code to delete the data goes here
            try {
                
                st = cn.createStatement();
                String  sql = "DELETE FROM hewan WHERE id = '"+ txtid.getText()+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus ");
                TampilData();
                Bersih();
           
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
 
         
            }
        }
    
    }//GEN-LAST:event_BtnhapusActionPerformed

    private void BtnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbatalActionPerformed
        // TODO add your handling code here:
        Bersih();
    }//GEN-LAST:event_BtnbatalActionPerformed

    private void TxtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCariKeyPressed
        // TODO add your handling code here:
        CariData();
    }//GEN-LAST:event_TxtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHewan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnbatal;
    private javax.swing.JButton Btnhapus;
    private javax.swing.JButton Btnsimpan;
    private javax.swing.JComboBox<String> Cmbcari;
    private javax.swing.JTable Tbldata;
    private javax.swing.JTextField TxtCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txthabitat;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtid_obat;
    private javax.swing.JTextField txtid_pemilik;
    private javax.swing.JTextField txtid_species;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
